### ISSUE TITLE
glooctl auth config

### ISSUE THREAD

**Issue by apobbati** [solo-io/glooctl#25]
Getting the following issue when running `glooctl upstream get`:

```
Unable to create storage client "failed to start kube config watcher with config bootstrap.KubeOptions{KubeConfig:\"/Users/apobbati/.kube/config\", MasterURL:\"\", Namespace:\"gloo-system\"}: No Auth Provider found for name \"oidc\""
```

My cluster is configured using OIDC for authentication.

How would I go about resolving it?

**Comment by ilackarms** [comment]
what's the output of `kubectl get upstream -n gloo-system` ?

**Comment by apobbati** [comment]
It's as follows:

```
NAME                                                           AGE
default-petstore-8080                                          10m
gloo-system-gloo-8081                                          12m
gloo-system-ingress-8080                                       12m
gloo-system-ingress-8443                                       12m
kube-system-kubernetes-dashboard-80                            12m
nginx-ingress-nginx-ingress-nginx-ingress-controller-443       12m
nginx-ingress-nginx-ingress-nginx-ingress-controller-80        12m
nginx-ingress-nginx-ingress-nginx-ingress-default-backend-80   12m
```

**Comment by ilackarms** [comment]
thanks for bringing this to our attention. it looks like the kubernetes `client-go` library no longer imports the OIDC package by default. we'll add it to `glooctl` right now so you can get glooin' !

see this issue here as reference: https://github.com/coreos/tectonic-forum/issues/99

**Comment by ilackarms** [comment]
@apobbati we updated and pushed (what we hope is) a fix. can you test for us with latest master?

**Comment by ilackarms** [comment]
btw, you can now use our latest release instead of having to `go get`: https://github.com/solo-io/glooctl/releases

**Comment by apobbati** [comment]
Works for me! Thanks for the quick response.
